### ISSUE TITLE
[Bug] Can't connect to ISPConfig 3

### ISSUE THREAD

**Issue by ImmensumUniversum** [FOSSBilling/ISPConfig-3#1]
### Describe the bug

When trying to establish a connection, I see an error "Server_Exception::__construct(): Argument FOSSBilling/FOSSBilling#2 ($variables) must be of type ?array, int given, called in /var/www/example.com/library/Server/Manager/Ispconfig3.php on line 541 (9998)"

### How to reproduce

1. ISPConfig 3 installed on Debian 11
2. In FossBilling go to "Configuration" => "Hosting plans and servers" => "New Server" and enter all data
3. After creation try to modify server data or click button "Test connection"

### Expected behavior

Tested the connection with HestiaCP in the same way - everything is OK

### FOSSBilling version

v0.3.0 stable

**Comment by jsonkenyon** [comment]
I'm currently working on a complete rewrite, hoping to have it done.  Docs for ISPConfig API calls are kinda meh at best.  Though I have successfully been able to get it to login and provide a session using RestAPI.  Everything else should in theory be pretty simple going forward.   Now that I'm starting to see how they want the api payload.

**Comment by jsonkenyon** [comment]
Working on this, so far I have gotten the following up and running with the RestAPI

- Login to get a session for the API.
- Can create accounts, and if client doesn't exist in ISP it will create them.
- Suspend/Un-suspend accounts. (I don't think this is going to count for any resellers, I'm not 100% sure on ISPConfig, so if you know how that works LTM)

Looking over the code of the old system it looks like I have to do the following left.

1. Create the DNS records for ISPConfig upon account creation
2. Change Package
3. Cancel Account
4. Change Account Password

**Comment by jsonkenyon** [comment]
### Update

I just got done, adding and making sure that the DNS gets created.  This marks the list as complete and I should have a pull request tomorrow to get it updated, and we will need some testers/feedback.

**This is still a big change, and I'm looking at improving the code further.  The goal of this round was just to get it working again, now its code cleanup, looking to see if we can add more features, and if we need to make further dns adds. **
